### ISSUE TITLE
POS Tagger error

### ISSUE THREAD

**Issue by Omerkorat** [mideind/GreynirSeq#53]
Hello,

When I try to run the POS tagger, I run into the following error, does anyone know what it means?

Traceback (most recent call last):
  File "/home/yugen/anaconda3/bin/greynirseq", line 8, in <module>
    sys.exit(main())
  File "/home/yugen/anaconda3/lib/python3.9/site-packages/greynirseq/cli/greynirseq_main.py", line 297, in main
    for result in handler.run(args.input):
  File "/home/yugen/anaconda3/lib/python3.9/site-packages/greynirseq/cli/greynirseq_main.py", line 70, in run
    yield from self.infer(batch)
  File "/home/yugen/anaconda3/lib/python3.9/site-packages/greynirseq/cli/greynirseq_main.py", line 102, in infer
    batch_labels = self.model.predict_ifd_labels(batch)  # type: ignore
  File "/home/yugen/anaconda3/lib/python3.9/site-packages/greynirseq/nicenlp/models/multilabel.py", line 234, in predict_ifd_labels
    labels = self.predict_labels(sentences)
  File "/home/yugen/anaconda3/lib/python3.9/site-packages/greynirseq/nicenlp/models/multilabel.py", line 227, in predict_labels
    cat_logits, attr_logits, word_mask = self.get_logits(sentences)
  File "/home/yugen/anaconda3/lib/python3.9/site-packages/greynirseq/nicenlp/models/multilabel.py", line 212, in get_logits
    (cat_logits, attr_logits), _extra = self.model(
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by peturorri** [comment]
Hi,

Can you please share the version of greynirseq you are using and the exact command and input you are running into problems with.

**Comment by Omerkorat** [comment]
How do I check the version?
I simply got the code by directly cloning from github, so should be the latest version.

The command I'm using is the same one from the readme:

`echo "Systurnar Guðrún og Monique átu einar um jólin á McDonalds ." | greynirseq pos --input -`

**Comment by peturorri** [comment]
There are currently some problems with outdated dependencies on main that make this difficult to install in some environments (including some of mine). I'm not sure how you installed it, but where I do manage to actually install (conda with Python 3.8.13) the command runs fine.

**Comment by Omerkorat** [comment]
Yeah, that seems to have been the issue. I tried it with Python 3.8 and it works. Thanks!

**Comment by peturorri** [comment]
Thanks for letting me know!
